services:
  - type: web
    name: word-world-refund-bank
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bankdb
          property: connectionString
    plan: free

databases:
  - name: bankdb
    plan: free
    region: frankfurt
    databaseName: bankdb
    user: bankuser